# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5207a1d5737619cd4953dab4d02475c1986207c1c1455cbf4a7487e89c57df324869a49fb01e7ac93ec0220b1d773c816ceb33436d0432a0062ed2db708f053

test:
  secret_key_base: 802cd36a3f9349f3d6a1f7feda035aacfaa70b05769d957ac9439f2168e0677afd6bfb8337fa1565f16e28b3d7b63e0e76330354467e41c949960e3e7a673302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
